services:
  db:
    ports:
      - "127.0.0.1:5432:5432"
    image: "docker.io/postgres:17-alpine"
    env_file:
      - .env
    volumes:
      - postgresql-data:/var/lib/postgresql/data/ # persist data even if container shuts down
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
volumes:
  postgresql-data: 