services:
  db:
    image: "postgres:17-alpine"
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - .env
    volumes:
      - postgresql-data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./logs:/var/log/postgresql
      - ./pg-entrypoint.sh:/pg-entrypoint.sh:ro
      - ./backup/wal:/backup/wal
    entrypoint: ["/pg-entrypoint.sh"]

volumes:
  postgresql-data:

