FROM node:22-alpine
WORKDIR /app
RUN npm i -g tsx
RUN npm i postgres
RUN npm i express
COPY src/entry.postgresSSE.ts ./server/
COPY tsconfig.json .
COPY db.ts .
EXPOSE 3010
CMD ["tsx", "server/entry.postgresSSE.ts"]